content_filters:
  omit_categories:
    - "Sports: Any professional or amateur sports news."
    - "Tabloid/Gossip: Celebrity or sensationalist content."
    - "Tragedy/Crime: Individual crimes or accidents."
    - "Low-Value: Listicles, ads, press releases."

categories:
  general:
    rss:
      - https://www.index.hr/rss
      - https://247newsaroundtheworld.com/feed/
      - https://abcnews.go.com/abcnews/internationalheadlines
    urls: []

  culture:
    rss:
      - https://www.newyorker.com/feed/culture
    urls: []

  science:
    rss:
      - https://www.sciencemag.org/rss/news_current.xml
    urls: []
