content_filters:
  omit_categories:
    - "Sports: Any professional or amateur sports news."
    - "Tabloid/Gossip: Celebrity or sensationalist content."
    - "Tragedy/Crime: Individual crimes or accidents."
    - "Low-Value: Listicles, ads, press releases."

categories:
  general:
    rss:
      - https://news.ycombinator.com/rss
      - https://www.reddit.com/r/worldnews/.rss
    urls: []

  culture:
    rss:
      - https://www.newyorker.com/feed/culture
    urls: []

  science:
    rss:
      - https://www.sciencemag.org/rss/news_current.xml
    urls: []
